### ISSUE TITLE
ignoring exclude_paths?

### ISSUE THREAD

**Issue by soderlind** [AtomLinter/linter-codeclimate#68]
macos 10.12.4
    codeclimate 0.63.3
    linter-codeclimate 0.2.4

The exclude_paths rules are followed when running `codeclimate analyze`, but in linter-codeclimate (phpcodesniffer) they are not:

![linter-codeclimate-exclude_paths](https://cloud.githubusercontent.com/assets/1649452/26098353/bd08d862-3a27-11e7-9982-e10a30b03673.png)

Below are  my .codeclimate.yml and phpcs.xml files:

```yml
---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
        standard: "phpcs.xml"
ratings:
  paths:
    - "**.js"
    - "**.php"
exclude_paths:
  - node_modules/**
  - languages/**
  - lib/cloudinary/**
  - lib/plugin-customizer/assets/twentysixteen/**
  - lib/Customizer/assets/js/boxshadow.js
```

```xml
<?xml version="1.0"?>
<ruleset name="Plugin Customizer">
	<description>The code standard for Plugin Customizer in WordPress.</description>

	<!-- ##### WordPress sniffs #####-->
	<rule ref="WordPress-Core">
		<exclude name="Generic.Files.LowercasedFilename" />
		<exclude name="WordPress.Files.FileName" />
		<exclude name="WordPress.Files.FileName.UnderscoresNotAllowed" />
	</rule>
</ruleset>
```
